# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: ZXHub
main: com.earth2me.essentials.spawn.EssentialsSpawn
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: TeamCity
website: http://tiny.cc/EssentialsCommands
description: Provides command to go to the server hub.
authors: [AngeloR42]
depend: [Essentials]
commands:
  setspawn:
    description: Set the spawnpoint to your current position.
    usage: /<command> <group>
    aliases: [esetspawn,setlobby,sethub]
  spawn:
    description: Teleport to the spawnpoint.
    usage: /<command> [player]
    aliases: [espawn,hub,lobby]
